
name: github-actions
on: [push]
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Run Super Linter
        uses: github/super-linter@v4
        env: 
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: github_actions
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name : Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17 # The Go version to download (if necessary) and use.
      - name: Build
        run: go build -v ./... 
      - name: Run Go Server
        run: go run main.go
      - name: Validate if the service is working or not.
        run: |
            sleep 5
            curl http://localhost:8000/health-checks