
name: github-actions
on: [push]
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
    - name: Starting CICD with gihub actions...
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        if: always()
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: github_actions
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: checkout code
      uses: actions/checkout@v2
    - name: Run Super Linter
      uses: github/super-linter@v4
        
    - name : Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 # The Go version to download (if necessary) and use.
    - name: Build
      run: go build -v ./... 
      
      
