
name: github-actions
on: [push]
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Run Super Linter
        uses: github/super-linter@v4
        env: 
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: github_actions
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name : Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17 # The Go version to download (if necessary) and use.
      - name: Build
        run: go build -v ./... 
      - name: Send slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        if: always()
      