
name: super-linter-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Run Super Linter
        uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine
        env: 
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: github_actions
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      